version: '3.7'

services:
  db:
    image: mysql
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d/
    command:
      --default-authentication-plugin=mysql_native_password
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8
      --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_PASS=123456
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
    restart: always

  redis:
    image: redis:5.0
    network_mode: bridge
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    command:
      redis-server /etc/redis/redis.conf

  web:
    build: ./src
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/usr/src/app
      - static_volume:/usr/src/app/static_cdn
      - media_volume:/usr/src/app/media_cdn
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=n!4t(1329vc_i!-(bxd5v$w=q(8r(07svi5ku6f@+8r&hw2t89
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 192.168.148.129 [::1]
      - SQL_ENGINE=django.db.backends.mysql
      - SQL_DATABASE=library
      - SQL_USER=root
      - SQL_PASSWORD=123456
      - SQL_HOST=db
      - SQL_PORT=3306
      - EMAIL_HOST='smtp.163.com'
      - EMAIL_PORT=25
      - EMAIL_HOST_USER='goblintechtest@163.com'
      - EMAIL_HOST_PASSWORD='smart123'
      - EMAIL_FROM='library<goblintechtest@163.com>'
      - CELERY_BROKER=redis://192.168.148.129:6379/5
      - CELERY_BACKEND=redis://192.168.148.129:6379/6
      - TZ=Asia/Shanghai
    depends_on:
      - db

  celery:
    build: ./src
    command: celery -A celery_tasks.main worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./src:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=n!4t(1329vc_i!-(bxd5v$w=q(8r(07svi5ku6f@+8r&hw2t89
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 192.168.148.129 [::1]
      - CELERY_BROKER=redis://192.168.148.129:6379/5
      - CELERY_BACKEND=redis://192.168.148.129:6379/6
    depends_on:
      - web
      - redis

  dashboard:
    build: ./src
    command: flower -A library --port=5555 --broker=redis://192.168.148.129:6379/5
    ports:
      - 5555:5555
    environment:
      - DEBUG=1
      - SECRET_KEY=sahu@!id&@^!ohqwu_asdasd&^!
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 192.168.148.129 [::1]
      - CELERY_BROKER=redis://192.168.148.129:6379/5
      - CELERY_BACKEND=redis://192.168.148.129:6379/6
    depends_on:
      - web
      - celery
      - redis

volumes:
  mysql_data:
  static_volume:
  media_volume: